# 🌟 Matrix & Vector Functions Demo
Notebook trình bày và minh họa các hàm từ **matrix.py** và **vector.py** với hiển thị đẹp.

In [1]:
from matrix import *
from vector import *
from IPython.display import display, Markdown

## 🧮 Matrix Demo

In [2]:
A = create_random_matrix(3,3)
B = create_random_matrix(3,3)
display(Markdown('### **Matrix A**'))
display(A)
display(Markdown('### **Matrix B**'))
display(B)

### **Matrix A**

array([[62,  0, 11],
       [42, 91, 99],
       [53, 57, 89]], dtype=int32)

### **Matrix B**

array([[ 2, 68, 72],
       [76, 28, 76],
       [30, 38, 43]], dtype=int32)

In [3]:
display(Markdown('###  Tổng hai ma trận'))
display(matrix_sum(A,B))

###  Tổng hai ma trận

array([[ 64,  68,  83],
       [118, 119, 175],
       [ 83,  95, 132]], dtype=int32)

In [4]:
display(Markdown('###  Hiệu hai ma trận'))
display(matrix_diff(A,B))

###  Hiệu hai ma trận

array([[ 60, -68, -61],
       [-34,  63,  23],
       [ 23,  19,  46]], dtype=int32)

In [5]:
display(Markdown('###  Tích từng phần tử'))
display(matrix_product_elementwise(A,B))

###  Tích từng phần tử

array([[ 124,    0,  792],
       [3192, 2548, 7524],
       [1590, 2166, 3827]], dtype=int32)

In [6]:
display(Markdown('###  Nhân ma trận (dot)'))
display(matrix_dot(A,B))

###  Nhân ma trận (dot)

array([[  454,  4634,  4937],
       [ 9970,  9166, 14197],
       [ 7108,  8582, 11975]], dtype=int32)

In [7]:
display(Markdown('###  Ma trận chuyển vị'))
display(matrix_transpose(A))

###  Ma trận chuyển vị

array([[62, 42, 53],
       [ 0, 91, 57],
       [11, 99, 89]], dtype=int32)

In [8]:
display(Markdown('###  Định thức ma trận'))
display(matrix_determinant(A))

###  Định thức ma trận

np.float64(125552.99999999996)

In [9]:
display(Markdown('###  Ma trận nghịch đảo'))
display(matrix_inverse(A))

###  Ma trận nghịch đảo

array([[ 0.01956146,  0.00499391, -0.00797273],
       [ 0.01201883,  0.03930611, -0.045208  ],
       [-0.01934641, -0.02814748,  0.0449372 ]])

In [10]:
display(Markdown('###  Hạng của ma trận'))
display(matrix_rank(A))

###  Hạng của ma trận

np.int64(3)

In [11]:
display(Markdown('###  Giá trị riêng & vector riêng'))
vals, vecs = matrix_eig(A)
display(vals)
display(vecs)

###  Giá trị riêng & vector riêng

array([169.46522134,  60.23498931,  12.29978935])

array([[-0.06179616, -0.75673072, -0.14443375],
       [-0.79479647,  0.64235147, -0.74382613],
       [-0.60372164,  0.12142162,  0.65258071]])

In [12]:
display(Markdown('###  Chuẩn Frobenius'))
display(matrix_norm(A))

###  Chuẩn Frobenius

np.float64(194.39650202614243)

In [13]:
display(Markdown('###  Trace (tổng đường chéo)'))
display(matrix_trace(A))

###  Trace (tổng đường chéo)

np.int64(242)

## 📌 Vector Demo

In [14]:
v1 = create_random_vector(5)
v2 = create_random_vector(5)
display(Markdown('### **Vector v1**'))
display(v1)
display(Markdown('### **Vector v2**'))
display(v2)

### **Vector v1**

array([62, 81, 17, 40, 64], dtype=int32)

### **Vector v2**

array([96, 30,  9, 41, 37], dtype=int32)

In [15]:
display(Markdown('###  Tổng hai vector'))
display(vector_sum(v1,v2))

###  Tổng hai vector

array([158, 111,  26,  81, 101], dtype=int32)

In [16]:
display(Markdown('###  Hiệu hai vector'))
display(vector_diff(v1,v2))

###  Hiệu hai vector

array([-34,  51,   8,  -1,  27], dtype=int32)

In [17]:
display(Markdown('###  Nhân từng phần tử'))
display(vector_product(v1,v2))

###  Nhân từng phần tử

array([5952, 2430,  153, 1640, 2368], dtype=int32)

In [18]:
display(Markdown('###  Tích vô hướng (dot)'))
display(vector_dot(v1,v2))

###  Tích vô hướng (dot)

np.int32(12543)

In [19]:
display(Markdown('###  Khoảng cách Euclid'))
display(vector_distance(v1,v2))

###  Khoảng cách Euclid

np.float64(67.46109990209172)

In [20]:
display(Markdown('###  Góc giữa hai vector'))
display(vector_angle(v1,v2))

###  Góc giữa hai vector

(np.float64(0.851242262455299), np.float64(0.5524483202976466))

In [21]:
display(Markdown('###  Kiểm tra quan hệ vector'))
display(check_relation(v1,v2))

###  Kiểm tra quan hệ vector

'Không vuông góc cũng không song song'

In [22]:
display(Markdown('###  Ghép nối vector'))
display(vector_concat(v1,v2))

###  Ghép nối vector

array([62, 81, 17, 40, 64, 96, 30,  9, 41, 37], dtype=int32)

In [23]:
display(Markdown('###  Đảo ngược vector'))
display(vector_reverse(v1))

###  Đảo ngược vector

array([64, 40, 17, 81, 62], dtype=int32)

In [24]:
display(Markdown('###  Giá trị duy nhất'))
display(vector_unique(v1))

###  Giá trị duy nhất

array([17, 40, 62, 64, 81], dtype=int32)

In [25]:
display(Markdown('###  Độ dài vector'))
display(vector_length(v1))

###  Độ dài vector

5

In [26]:
display(Markdown('###  Phần tử ngẫu nhiên'))
display(vector_random_element(v1))

###  Phần tử ngẫu nhiên

np.int32(40)